# This file has been generated by ./pkgs/misc/vim-plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, fetchFromGitHub, overrides ? (self: super: {}) }:

let
  packages = ( self:
{
  clever-f-vim = buildVimPluginFrom2Nix {
    pname = "clever-f-vim";
    version = "2020-01-25";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "clever-f.vim";
      rev = "e2085bbeaf69ffadd7f9bd390c36633fa70c01f4";
      sha256 = "0r8raad7yy1qsi9ajajsbiq1ayppkp1bjji5dsj8sdwycmbyvgfw";
    };
  };

  distilled-vim = buildVimPluginFrom2Nix {
    pname = "distilled-vim";
    version = "2019-08-02";
    src = fetchFromGitHub {
      owner = "KKPMW";
      repo = "distilled-vim";
      rev = "58fe63d119419db9b6924ec9fe90504f4642afee";
      sha256 = "0j3pwclm6j2z0imxsa3km85gnnwhxbc69xlrwnm62l64lfnxammw";
    };
  };

  flatlandia = buildVimPluginFrom2Nix {
    pname = "flatlandia";
    version = "2014-05-05";
    src = fetchFromGitHub {
      owner = "jordwalke";
      repo = "flatlandia";
      rev = "05069c3777c463b25b609dca8dccacf9f75e2ce3";
      sha256 = "04mk80zaxjxh9hdy9ll12ri9pq6s0p0lz1myg7yfz8rgyd74kaqz";
    };
  };

  git-messenger-vim = buildVimPluginFrom2Nix {
    pname = "git-messenger-vim";
    version = "2020-01-27";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "git-messenger.vim";
      rev = "422a9334b9fe1dec9ecea6c0a1c48da71340e45f";
      sha256 = "18ws17c0fx2jsfwkfc5mln5853sssflg1l0xwwy8j9ldryy3x1z8";
    };
  };

  iceberg-vim = buildVimPluginFrom2Nix {
    pname = "iceberg-vim";
    version = "2019-11-07";
    src = fetchFromGitHub {
      owner = "cocopon";
      repo = "iceberg.vim";
      rev = "dc4b4b5838d126c22c44229a3ee170f6ac79ba86";
      sha256 = "1hicambipbgwf22fax782gpfmcndcpikj3bpf8v91wd5fxm7ik74";
    };
  };

  nord-vim = buildVimPluginFrom2Nix {
    pname = "nord-vim";
    version = "2019-12-17";
    src = fetchFromGitHub {
      owner = "arcticicestudio";
      repo = "nord-vim";
      rev = "f06189a4c054fe8c22e46aca4d451e03456f2283";
      sha256 = "0gk4zq0gz3nnwfkldswg9bjpk0gf6d6mgfzcgvj0pnlbja6ass81";
    };
  };

  nova-vim = buildVimPluginFrom2Nix {
    pname = "nova-vim";
    version = "2019-08-27";
    src = fetchFromGitHub {
      owner = "trevordmiller";
      repo = "nova-vim";
      rev = "e587d14c655a4d2d048556eaaa5419a14f17826a";
      sha256 = "0qdr84iykm8jrfl5q4clqv335blp3lj57isg0ylz1wak1gkn9dx8";
    };
  };

  vim-altr = buildVimPluginFrom2Nix {
    pname = "vim-altr";
    version = "2019-05-24";
    src = fetchFromGitHub {
      owner = "kana";
      repo = "vim-altr";
      rev = "fba055cf3b83a1ada5b05d694fbefd024aa93289";
      sha256 = "0q1zzfmzq1r6lfif2apx0pb82pa7ar84fyxl6l8dkal2712rsr5w";
    };
  };

  vim-clang-format = buildVimPluginFrom2Nix {
    pname = "vim-clang-format";
    version = "2019-05-15";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "vim-clang-format";
      rev = "95593b67723f23979cd7344ecfd049f2f917830f";
      sha256 = "0n0k13k63l8n0ixs4zrhlz923apvdp2mldadxqlhmvsvncmlqmpn";
    };
  };

  vim-clap = buildVimPluginFrom2Nix {
    pname = "vim-clap";
    version = "2020-02-03";
    src = fetchFromGitHub {
      owner = "liuchengxu";
      repo = "vim-clap";
      rev = "929cff01be4b6554b890db24802d645571926121";
      sha256 = "1nwmw9fkqn37zrsbqjbjsir475svj89iyg53d7pchdj2i2dic3lz";
    };
  };

  vim-pasta = buildVimPluginFrom2Nix {
    pname = "vim-pasta";
    version = "2018-09-08";
    src = fetchFromGitHub {
      owner = "sickill";
      repo = "vim-pasta";
      rev = "cb4501a123d74fc7d66ac9f10b80c9d393746c66";
      sha256 = "14rswwx24i75xzgkbx1hywan1msn2ki26353ly2pyvznnqss1pwq";
    };
  };

  vim-substrata = buildVimPluginFrom2Nix {
    pname = "vim-substrata";
    version = "2020-01-07";
    src = fetchFromGitHub {
      owner = "arzg";
      repo = "vim-substrata";
      rev = "4ef623320fb28bf5ece6da04d86e4de5759ec472";
      sha256 = "0gz773546283izlc1pxvqj3ydj7aa2aqhpfq9mvy3dxfad26cwrz";
    };
  };

  vim-textobj-variable-segment = buildVimPluginFrom2Nix {
    pname = "vim-textobj-variable-segment";
    version = "2019-12-30";
    src = fetchFromGitHub {
      owner = "Julian";
      repo = "vim-textobj-variable-segment";
      rev = "78457d4322b44bf89730e708b62b69df48c39aa3";
      sha256 = "14dcrnk83hj4ixrkdgjrk9cf0193f82wqckdzd4w0b76adf3habj";
    };
  };

  vim-visual-star-search = buildVimPluginFrom2Nix {
    pname = "vim-visual-star-search";
    version = "2015-11-05";
    src = fetchFromGitHub {
      owner = "bronson";
      repo = "vim-visual-star-search";
      rev = "fa55818903301d61cef67341d3524a63a14bc033";
      sha256 = "1ny6sdl08mbh5j3fvsznlgxdv2hip190dmsgs22gygn8wpj2xc8l";
    };
  };

  vimagit = buildVimPluginFrom2Nix {
    pname = "vimagit";
    version = "2020-01-12";
    src = fetchFromGitHub {
      owner = "jreybert";
      repo = "vimagit";
      rev = "bf7b16e99e075b019e56f2fbfb96c493ca3635e2";
      sha256 = "1f7gvlhrvvkf69y5vfrkvidhx8aa03n1aqmdhk9qjd6sglfg5w0i";
    };
  };

  vista-vim = buildVimPluginFrom2Nix {
    pname = "vista-vim";
    version = "2020-01-30";
    src = fetchFromGitHub {
      owner = "liuchengxu";
      repo = "vista.vim";
      rev = "dd5769ec7a1e4c2c8927a6af4d26f88524faa60c";
      sha256 = "0jad10lx3lvfy56gnk50lpcbwyxk16yxm5i1p3r3zwsqra03kw5h";
    };
  };

});
in lib.fix' (lib.extends overrides packages)
