# This file has been generated by ./pkgs/misc/vim-plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, fetchFromGitHub, overrides ? (self: super: {}) }:

let
  packages = ( self:
{
  clever-f-vim = buildVimPluginFrom2Nix {
    pname = "clever-f-vim";
    version = "2019-08-09";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "clever-f.vim";
      rev = "baceb2c9d1fa0850bbf839cd2c8c0a9bbe524ff5";
      sha256 = "17i8p9sd7cxwdg8wi324dzqllkjrwm8fp9927gnh0vgcjw0rs47k";
    };
  };

  distilled-vim = buildVimPluginFrom2Nix {
    pname = "distilled-vim";
    version = "2019-08-02";
    src = fetchFromGitHub {
      owner = "KKPMW";
      repo = "distilled-vim";
      rev = "58fe63d119419db9b6924ec9fe90504f4642afee";
      sha256 = "0j3pwclm6j2z0imxsa3km85gnnwhxbc69xlrwnm62l64lfnxammw";
    };
  };

  flatlandia = buildVimPluginFrom2Nix {
    pname = "flatlandia";
    version = "2014-05-05";
    src = fetchFromGitHub {
      owner = "jordwalke";
      repo = "flatlandia";
      rev = "05069c3777c463b25b609dca8dccacf9f75e2ce3";
      sha256 = "04mk80zaxjxh9hdy9ll12ri9pq6s0p0lz1myg7yfz8rgyd74kaqz";
    };
  };

  git-messenger-vim = buildVimPluginFrom2Nix {
    pname = "git-messenger-vim";
    version = "2019-10-13";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "git-messenger.vim";
      rev = "c7d836d058613c3d4e797925d223b03c53553b63";
      sha256 = "0liv2wahz4fjjlz2ysvk3i9mb1q2asd7acsgcmicysl7fqd9x4i4";
    };
  };

  iceberg-vim = buildVimPluginFrom2Nix {
    pname = "iceberg-vim";
    version = "2019-11-07";
    src = fetchFromGitHub {
      owner = "cocopon";
      repo = "iceberg.vim";
      rev = "dc4b4b5838d126c22c44229a3ee170f6ac79ba86";
      sha256 = "1hicambipbgwf22fax782gpfmcndcpikj3bpf8v91wd5fxm7ik74";
    };
  };

  nord-vim = buildVimPluginFrom2Nix {
    pname = "nord-vim";
    version = "2019-05-25";
    src = fetchFromGitHub {
      owner = "arcticicestudio";
      repo = "nord-vim";
      rev = "9f7ce848723f69e33792e5606091bbfd5739d253";
      sha256 = "1n6kdnll5jh92kfbwwm8544mpp7c2awqsaps91agqjd3nwa5x27x";
    };
  };

  nova-vim = buildVimPluginFrom2Nix {
    pname = "nova-vim";
    version = "2019-08-27";
    src = fetchFromGitHub {
      owner = "trevordmiller";
      repo = "nova-vim";
      rev = "e587d14c655a4d2d048556eaaa5419a14f17826a";
      sha256 = "0qdr84iykm8jrfl5q4clqv335blp3lj57isg0ylz1wak1gkn9dx8";
    };
  };

  vim-altr = buildVimPluginFrom2Nix {
    pname = "vim-altr";
    version = "2019-05-24";
    src = fetchFromGitHub {
      owner = "kana";
      repo = "vim-altr";
      rev = "fba055cf3b83a1ada5b05d694fbefd024aa93289";
      sha256 = "0q1zzfmzq1r6lfif2apx0pb82pa7ar84fyxl6l8dkal2712rsr5w";
    };
  };

  vim-clang-format = buildVimPluginFrom2Nix {
    pname = "vim-clang-format";
    version = "2019-05-15";
    src = fetchFromGitHub {
      owner = "rhysd";
      repo = "vim-clang-format";
      rev = "95593b67723f23979cd7344ecfd049f2f917830f";
      sha256 = "0n0k13k63l8n0ixs4zrhlz923apvdp2mldadxqlhmvsvncmlqmpn";
    };
  };

  vim-clap = buildVimPluginFrom2Nix {
    pname = "vim-clap";
    version = "2019-11-21";
    src = fetchFromGitHub {
      owner = "liuchengxu";
      repo = "vim-clap";
      rev = "849747572e492da00d02b63a8e04db243c1a8547";
      sha256 = "0cysjwqzv2b3pvbmql1h7jhlbgnkjjdxy43kvd16ps8nlyll0r41";
    };
  };

  vim-pasta = buildVimPluginFrom2Nix {
    pname = "vim-pasta";
    version = "2018-09-08";
    src = fetchFromGitHub {
      owner = "sickill";
      repo = "vim-pasta";
      rev = "cb4501a123d74fc7d66ac9f10b80c9d393746c66";
      sha256 = "14rswwx24i75xzgkbx1hywan1msn2ki26353ly2pyvznnqss1pwq";
    };
  };

  vim-substrata = buildVimPluginFrom2Nix {
    pname = "vim-substrata";
    version = "2019-10-30";
    src = fetchFromGitHub {
      owner = "arzg";
      repo = "vim-substrata";
      rev = "9a6406e2aa6a4b74146935df139993db9f8416d4";
      sha256 = "0p7py0h6d05604xs94jm5icra8hm98bqgamhn1z6ai1h1rcm2axi";
    };
  };

  vim-textobj-variable-segment = buildVimPluginFrom2Nix {
    pname = "vim-textobj-variable-segment";
    version = "2019-05-05";
    src = fetchFromGitHub {
      owner = "Julian";
      repo = "vim-textobj-variable-segment";
      rev = "1af9cdef58a4072dddbe926e7c8c53903e97b70a";
      sha256 = "0spfbc30sli7ckpfbmjspfrbcg9dq5k0aimzbxx06rimbba8f846";
    };
  };

  vim-visual-star-search = buildVimPluginFrom2Nix {
    pname = "vim-visual-star-search";
    version = "2015-11-05";
    src = fetchFromGitHub {
      owner = "bronson";
      repo = "vim-visual-star-search";
      rev = "fa55818903301d61cef67341d3524a63a14bc033";
      sha256 = "1ny6sdl08mbh5j3fvsznlgxdv2hip190dmsgs22gygn8wpj2xc8l";
    };
  };

  vimagit = buildVimPluginFrom2Nix {
    pname = "vimagit";
    version = "2019-07-24";
    src = fetchFromGitHub {
      owner = "jreybert";
      repo = "vimagit";
      rev = "94762b1356ebdcb8ec486a86f45e69ef77a69465";
      sha256 = "1p8izqdkx8g1aqmq9a2qm506bs4mvc4xdbzkh2k5xprm5vc14z0s";
    };
  };

  vista-vim = buildVimPluginFrom2Nix {
    pname = "vista-vim";
    version = "2019-11-20";
    src = fetchFromGitHub {
      owner = "liuchengxu";
      repo = "vista.vim";
      rev = "44ad0dab12a92c0ee530941f1349d3814a551696";
      sha256 = "1arnks7hh2n8dwhybv048hs45jlmxqjxs03qgyp7za4dmkkw6lag";
    };
  };

});
in lib.fix' (lib.extends overrides packages)
